name: Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      data: "${{steps.step_id.outputs.data_in}}"
    steps:
      - id: step_id
        run: |
          echo "data_in=1" >> $GITHUB_OUTPUT
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    outputs:
      data: "${{steps.step_id.outputs.data_in}}"
    steps:
      - id: step_id
        run: |
          echo "data_in=3" >> $GITHUB_OUTPUT

  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Gui email voi attachment neu (200)
        if: $((${{needs.job1.outputs.data}} + ${{needs.job2.outputs.data}})) == 3
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: nvbang14061992@gmail.com
          password: ${{ secrets.GMAIL_APP_PASS }}
          subject: "Tieu de 1"
          body: "day la noi dung - ${{needs.job1.outputs.data}} - ${{needs.job2.outputs.data}}"
          to: nvbang14061992@gmail.com
          from: nvbang14061992@gmail.com
